name: BuildServerManager
version: ${project.version}
main: de.dieserfab.buildservermanager.BSM
author: DieserFab
commands:
  maps:
    aliases: [maps, map, m]
  gamemode:
    aliases: [gamemode, gm]
  difficulty:
    aliases: [diff, difficulty]