name: BuildServerManager
version: 1.4.1
main: de.dieserfab.buildservermanager.BSM
author: DieserFab
commands:
  maps:
    aliases: [maps, map, m]
  gamemode:
    aliases: [gamemode, gm]
  difficulty:
    aliases: [diff, difficulty]
  nightvision:
    aliases: [nv, nightvision]